SELECT *
FROM user_shopping_behavior



--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from user_shopping_behavior
group by gender



--Q2. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM user_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue desc;

/* Q3.

Location-level revenue concentration — what % of total revenue comes from your top 10 states,
and is there a long tail worth marketing investment vs. one not worth the spend?

*/

WITH loc_rev AS (
  SELECT location, SUM(purchase_amount) AS revenue
  FROM user_shopping_behavior GROUP BY location
)
SELECT location, revenue,
       ROUND(100.0*revenue/SUM(revenue) OVER (),2) AS pct_of_total,
       ROUND(100.0*SUM(revenue) OVER (ORDER BY revenue DESC)/SUM(revenue) OVER (),2) AS cumulative_pct
FROM loc_rev
ORDER BY revenue DESC;







--------------------

-- Q4. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from user_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q5. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM user_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


 /*
Q6. Which category × season combinations are under-indexed — i.e., 
where is there a mismatch between inventory categories and seasonal demand?
*/
SELECT season, category,
       COUNT(*) AS orders,
       SUM(purchase_amount) AS revenue,
       ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER (PARTITION BY season),2) AS pct_of_season_orders
FROM user_shopping_behavior
GROUP BY season, category
ORDER BY season, revenue DESC;




----------


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM user_shopping_behavior)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


/*
Q8. Customer value tiering (RFM-lite) — combine previous_purchases (frequency proxy) with purchase_amount (monetary)
to rank customers into value tiers, since there's no repeat-transaction date in this dataset.
*/
SELECT customer_id,
       previous_purchases,
       purchase_amount,
       NTILE(4) OVER (ORDER BY previous_purchases DESC) AS frequency_quartile,
       NTILE(4) OVER (ORDER BY purchase_amount DESC) AS monetary_quartile
FROM user_shopping_behavior;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM user_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;


------------

--Q10. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM user_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q11. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from user_shopping_behavior 
where discount_applied = 'Yes' and purchase_amount >=
                                            (select AVG(purchase_amount) from user_shopping_behavior)



--Q12. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM user_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;






--Q13. Is there a "discount dependency" segment — customers who only buy when there's a discount, 
-- and how much revenue would you lose if you paused discounting?

SELECT discount_applied,
       COUNT(*) AS orders,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue,
       ROUND(100.0*SUM(purchase_amount)/SUM(SUM(purchase_amount)) OVER (),2) AS pct_of_total_revenue
FROM user_shopping_behavior
GROUP BY discount_applied;

--------------
--Q14. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from user_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

/*
Q15. Shipping type vs. review rating — does faster/premium shipping correlate with customer satisfaction, not just spend?
*/
SELECT shipping_type,
       COUNT(*) AS orders,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(AVG(review_rating::numeric),2) AS avg_rating
FROM user_shopping_behavior
GROUP BY shipping_type
ORDER BY avg_rating DESC;


/*
Q16. Payment method vs. average order value — which payment methods are associated with higher spend,
and should we push customers toward them?
*/
SELECT payment_method,
       COUNT(*) AS orders,
       ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM user_shopping_behavior
GROUP BY payment_method
ORDER BY avg_order_value DESC;

--------------


/*
Q17. Purchase frequency vs. average review rating — do your most frequent buyers actually rate you higher, 
or is loyalty happening despite mediocre satisfaction?
*/

SELECT frequency_of_purchases,
       COUNT(*) AS customers,
       ROUND(AVG(review_rating::numeric),2) AS avg_rating,
       ROUND(AVG(purchase_amount),2) AS avg_spend
FROM user_shopping_behavior
GROUP BY frequency_of_purchases
ORDER BY avg_rating DESC;

/*
Q18. Size and Color — are there low-rated, high-return-risk combinations (proxy via low review_rating) 
concentrated in specific product attributes?
*/

SELECT category, size, color,
       COUNT(*) AS orders,
       ROUND(AVG(review_rating::numeric),2) AS avg_rating
FROM user_shopping_behavior
GROUP BY category, size, color
HAVING COUNT(*) >= 10
ORDER BY avg_rating ASC
LIMIT 15;


















